// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.1
// source: proto/authen/authen.proto

package authen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthenServiceClient is the client API for AuthenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthenServiceClient interface {
	VerifyToken(ctx context.Context, in *String, opts ...grpc.CallOption) (*Bool, error)
}

type authenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenServiceClient(cc grpc.ClientConnInterface) AuthenServiceClient {
	return &authenServiceClient{cc}
}

func (c *authenServiceClient) VerifyToken(ctx context.Context, in *String, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/authen.AuthenService/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenServiceServer is the server API for AuthenService service.
// All implementations must embed UnimplementedAuthenServiceServer
// for forward compatibility
type AuthenServiceServer interface {
	VerifyToken(context.Context, *String) (*Bool, error)
	mustEmbedUnimplementedAuthenServiceServer()
}

// UnimplementedAuthenServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthenServiceServer struct {
}

func (UnimplementedAuthenServiceServer) VerifyToken(context.Context, *String) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedAuthenServiceServer) mustEmbedUnimplementedAuthenServiceServer() {}

// UnsafeAuthenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthenServiceServer will
// result in compilation errors.
type UnsafeAuthenServiceServer interface {
	mustEmbedUnimplementedAuthenServiceServer()
}

func RegisterAuthenServiceServer(s grpc.ServiceRegistrar, srv AuthenServiceServer) {
	s.RegisterService(&AuthenService_ServiceDesc, srv)
}

func _AuthenService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authen.AuthenService/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenServiceServer).VerifyToken(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthenService_ServiceDesc is the grpc.ServiceDesc for AuthenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authen.AuthenService",
	HandlerType: (*AuthenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _AuthenService_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/authen/authen.proto",
}
